chore: improved release

diff --git a/.github/workflows/release-please.yml b/.github/workflows/release-please.yml
--- a/.github/workflows/release-please.yml
+++ b/.github/workflows/release-please.yml
@@ -1,20 +1,84 @@
 on:
-  workflow_dispatch:
   push:
     branches:
       - main
-
-permissions:
-  contents: write
-  pull-requests: write
-
+  workflow_dispatch:
 name: release-please
-
+env:
+  ACTION_NAME: action-terraform
 jobs:
-  release-please:
+  build:
     runs-on: ubuntu-latest
     steps:
+    - uses: actions/checkout@v4
+    - uses: actions/setup-node@v4
+      with:
+        node-version-file: ".nvmrc"
+    - name: install
+      run: npm ci
+    - name: build
+      run: npm run build
+    - name: commit
+      run: |-
+        set -e
+        # get current commit hash
+        CURRENT_HASH=$(git rev-parse HEAD)
+        # get last commit hash of last build lib
+        LAST_BUILD_HASH=$(git log --author=google-github-actions-bot -1 --pretty=format:"%H")
+        DIFF=""
+        # build and commit lib if diff
+        git config --global user.name "actions-bot"
+        git config user.email 'github-actions-bot@google.com'
+        git add lib/
+        git diff-index --quiet HEAD || git commit -m "chore: build lib ${ACTION_NAME}"
+        # if last commit hash of last build lib was found, get logs of commits in btw for PR body
+        if [ -z "$LAST_BUILD_HASH" ]
+        then
+              echo "Unable to find last commit by bot, skipping diff gen"
+        else
+              DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
+              echo $DIFF
+        fi
+        # set env vars
+        echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
+        echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
+        echo 'DIFF<<EOF' >> $GITHUB_ENV
+        echo "${DIFF}" >> $GITHUB_ENV
+        echo 'EOF' >> $GITHUB_ENV
+    - name: Create PR with lib
+      uses: peter-evans/create-pull-request@v5
+      with:
+        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
+        commit-message: Build lib
+        author: "actions-bot <github-actions-bot@google.com>"
+        title: "chore: build lib"
+        body: |
+          Build lib PR
+          ${{env.DIFF}}
+        labels: automated pr
+        branch: create-pull-request/build-lib
+        delete-branch: true
+        push-to-fork: google-github-actions-bot/${{env.ACTION_NAME}}
+  release-please-release:
+    runs-on: ubuntu-latest
+    needs: [build]
+    steps:
       - uses: google-github-actions/release-please-action@v4
+        id: release
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
+          skip-github-pull-request: true
+  release-please-pr:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - release-please-release
+    steps:
+      - id: release-pr
+        uses: google-github-actions/release-please-action@v4
+        with:
+          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
+          release-type: node
+          fork: true
+          skip-github-release: true
